/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  DigutilCountdownTimer as DuCountdownTimer
} from './components/du-countdown-timer/du-countdown-timer';

declare global {
  interface HTMLDuCountdownTimerElement extends DuCountdownTimer, HTMLElement {
  }
  var HTMLDuCountdownTimerElement: {
    prototype: HTMLDuCountdownTimerElement;
    new (): HTMLDuCountdownTimerElement;
  };
  interface HTMLElementTagNameMap {
    "du-countdown-timer": HTMLDuCountdownTimerElement;
  }
  interface ElementTagNameMap {
    "du-countdown-timer": HTMLDuCountdownTimerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "du-countdown-timer": JSXElements.DuCountdownTimerAttributes;
    }
  }
  namespace JSXElements {
    export interface DuCountdownTimerAttributes extends HTMLAttributes {
      timeTarget?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
